name: tp0

services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=Juan
      - APELLIDO=Perez
      - DOCUMENTO=19782345
      - NACIMIENTO=2000-01-01
      - NUMERO=6789
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - NOMBRE=Maria
      - APELLIDO=Gomez
      - DOCUMENTO=29182342
      - NACIMIENTO=1999-05-12
      - NUMERO=9321
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - NOMBRE=Pedro
      - APELLIDO=Lopez
      - DOCUMENTO=46782642
      - NACIMIENTO=1998-07-23
      - NUMERO=8923
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - NOMBRE=Ana
      - APELLIDO=Martinez
      - DOCUMENTO=42783001
      - NACIMIENTO=1997-11-30
      - NUMERO=4987
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - NOMBRE=Luis
      - APELLIDO=Hernandez
      - DOCUMENTO=22374590
      - NACIMIENTO=1996-03-15
      - NUMERO=7891
    volumes:
      - ./client/config.yaml:/config.yaml
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
